import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider,
  SignUp,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat with Pdf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#10b981", // matches your toast success color
          borderRadius: "0.5rem",
        },
      }}
    >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="flex justify-center items-center">
        <SignedOut>
          <SignUp 
            appearance={{
              elements: {
                card: "shadow-2xl border border-gray-200 rounded-2xl",
                headerTitle: "text-2xl font-bold text-gray-900",
                headerSubtitle: "text-gray-500",
                formButtonPrimary: "shadow-md transition-all hover:scale-[1.02]",
                socialButtonsBlockButton: "border-gray-300 hover:bg-gray-50 transition-colors",
              }
            }}
          />
        </SignedOut>
        </section>
        <SignedIn>
        {children}
        </SignedIn>
      </body>
    </html>
    </ClerkProvider>
  );
}
